import {CommonModule} from '@angular/common';
import {Component,computed,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {ApiService,Budget,Category,Debt,Goal,Summary} from './api.service';
type View='dashboard'|'movimientos'|'presupuestos'|'metas'|'deudas'|'reportes';
interface Tx{id:string;name:string;categoryId:string;category:string;date:string;rawDate:string;amount:number;type:'income'|'expense';icon:string;color:string;paymentMethod:string}

@Component({selector:'app-root',imports:[CommonModule,FormsModule],templateUrl:'./app.html',styleUrls:['./app.scss','./login.scss','./crud.scss']})
export class App{
 api=inject(ApiService);loading=signal(false);error=signal('');summary=signal<Summary>({income:0,expenses:0,balance:0,saved:0,pendingDebt:0});categories=signal<Category[]>([]);budgets=signal<Budget[]>([]);goals=signal<Goal[]>([]);debts=signal<Debt[]>([]);txs=signal<Tx[]>([]);
 view=signal<View>('dashboard');dark=signal(false);menu=signal(false);modal=signal(false);query=signal('');type=signal('Todos');formType=signal<'income'|'expense'>('expense');draft:any={};
 nav=[['dashboard','Inicio','⌂'],['movimientos','Movimientos','↕'],['presupuestos','Presupuestos','▣'],['metas','Metas de ahorro','◎'],['deudas','Deudas','▤'],['reportes','Reportes','◫']] as const;
 isAdmin=computed(()=>this.api.user()?.role==='Admin');
 filtered=computed(()=>this.txs().filter(t=>(this.type()==='Todos'||(this.type()==='Ingresos'&&t.type==='income')||(this.type()==='Gastos'&&t.type==='expense'))&&(t.name+t.category).toLowerCase().includes(this.query().toLowerCase())));
 metricCards=computed(()=>[['↙','Ingresos del mes',this.money(this.summary().income),'movimientos','mint'],['↗','Gastos del mes',this.money(this.summary().expenses),'movimientos','peach'],['◈','Balance disponible',this.money(this.summary().balance),'reportes','blue'],['◎','Total ahorrado',this.money(this.summary().saved),'metas','purple'],['▤','Deuda pendiente',this.money(this.summary().pendingDebt),'deudas','peach']]);
 constructor(){if(this.api.authenticated())this.loadData()}
 login(email:string,password:string){this.loading.set(true);this.error.set('');this.api.login(email,password).subscribe({next:()=>this.loadData(),error:e=>{this.loading.set(false);this.error.set(e.error?.message||'No fue posible iniciar sesión. Comprueba que la API esté activa.')}})}
 loadData(){this.loading.set(true);this.api.initialData().subscribe({next:d=>{this.summary.set(d.summary);this.categories.set(d.categories);this.budgets.set(d.budgets);this.goals.set(d.goals);this.debts.set(d.debts);this.txs.set(d.transactions.map(t=>({id:t.id,name:t.name,categoryId:t.categoryId,category:t.category,date:new Date(t.date).toLocaleDateString('es-CL',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}),rawDate:t.date,amount:t.type==='income'?t.amount:-t.amount,type:t.type,icon:t.type==='income'?'↙':'↗',color:t.type==='income'?'mint':'peach',paymentMethod:t.paymentMethod})));this.loading.set(false)},error:()=>{this.loading.set(false);this.error.set('No se pudo conectar con la API.')}})}
 money(n:number){return new Intl.NumberFormat('es-CL',{style:'currency',currency:'CLP',maximumFractionDigits:0}).format(Math.abs(n||0))}
 select(v:string){this.view.set(v as View);this.menu.set(false)} categoriesFor(type:string){return this.categories().filter(c=>c.type===type)} percent(a:number,b:number){return b?Math.min(100,Math.round(a/b*100)):0}
 openForm(item?:any){if(!this.isAdmin())return;const now=new Date();this.draft=item?{...item}:{type:'expense',paymentMethod:'Transferencia',categoryId:this.categoriesFor('expense')[0]?.id,limit:0,month:now.getMonth()+1,year:now.getFullYear(),targetAmount:0,currentAmount:0,targetDate:now.toISOString().slice(0,10),totalAmount:0,paidAmount:0,dueDate:now.toISOString().slice(0,10),installments:1};if(this.draft.targetDate)this.draft.targetDate=this.draft.targetDate.slice(0,10);if(this.draft.dueDate)this.draft.dueDate=this.draft.dueDate.slice(0,10);if(this.draft.amount)this.draft.amount=Math.abs(this.draft.amount);this.formType.set(this.draft.type||'expense');this.error.set('');this.modal.set(true)}
    save(){let resource='',body:any={};if(this.view()==='movimientos'){resource='transactions';body={description:this.draft.name,amount:+this.draft.amount,type:this.formType(),categoryId:this.draft.categoryId,paymentMethod:this.draft.paymentMethod||'Transferencia',date:this.draft.rawDate}}if(this.view()==='presupuestos'){resource='budgets';body={categoryId:this.draft.categoryId||null,limit:+this.draft.limit,month:+this.draft.month,year:+this.draft.year}}if(this.view()==='metas'){resource='savings-goals';body={name:this.draft.name,targetAmount:+this.draft.targetAmount,currentAmount:+this.draft.currentAmount,targetDate:this.draft.targetDate,description:this.draft.description||''}}if(this.view()==='deudas'){resource='debts';body={name:this.draft.name,entity:this.draft.entity||'',totalAmount:+this.draft.totalAmount,paidAmount:+this.draft.paidAmount,dueDate:this.draft.dueDate,installments:+this.draft.installments}}if(!resource)return;this.loading.set(true);this.api.save(resource,body,this.draft.id).subscribe({next:()=>{this.modal.set(false);this.loadData()},error:(e:any)=>{this.loading.set(false);this.error.set(e.error?.message||'No fue posible guardar. Revisa los datos.')}})}
 remove(resource:string,id:string){if(!this.isAdmin()||!confirm('¿Eliminar este registro definitivamente?'))return;this.api.remove(resource,id).subscribe({next:()=>this.loadData(),error:()=>this.error.set('No fue posible eliminar el registro.')})}
}
